
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://chyiyenwang.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

# baseurl: /personal-jekyll-theme

# Google tracking id to track your visitors

google-tracking-id: "UA-35880426-4"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

# force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Chyi Wang"
title: "{ Chyi Wang }"
description: "Website of Chyi Wang"
keywords: "wang, chyi, personal, jekyll, theme"
favicon: "/img/favicon.ico"
404-img: "/img/labtocat.png"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/background.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 2500
lines: # You can add HTML Tags in the Text
  - text: "Chyi Wang"
  - text: "Web Developer"
  - text: "Life-long learner"
  - text: "Adventurer"

me-img: "/img/chyi.png"

################
# Web app mode #
################

# web-app-mode: True

# # Icons for Web App mode

# icon-36p: "/img/web-app/icon-36p.png"
# icon-48p: "/img/web-app/icon-48p.png"
# icon-72p: "/img/web-app/icon-72p.png"
# icon-96p: "/img/web-app/icon-96p.png"
# icon-144p: "/img/web-app/icon-144p.png"
# icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "chyiyenwang"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/marvel.png"
    date: ""
    description: "<h4><a href='http://searchmarvel.herokuapp.com/' target='_blank'>Search Marvel</a></h4><small>This is a MEAN stack app using socket.io, and consuming the Twitter API to create a Marvel Comics wiki. While growing up I've always enjoyed reading comics so I wanted to create an app that reflects that. I created an API to hold relevant information for most comic book characters in the Marvel universe. This app utilizes two-way binding from Angular to search in real-time for the users favorite (or not so favorite) comic book character and retrieving biographical information about that character. The latest original tweets about that character are then shown in each character page.</small>"
  - image: "/img/timeline/halfway.png"
    date: ""
    description: "<h4><a href='https://halfway-chyiwang.herokuapp.com/' target='_blank'>Halfway</a></h4><small>This is a full stack web app utilizing Express and Node.js for the backend. This application finds a halfway destination (ie. coffee shop, restaurant, bar, etc) between two addresses by consuming the Google Maps Geolocation, Directions, and Places API. The inspiration for this app came from being frustrated with trying to find an actual halfway destination between myself and my friends.</small>"
  - image: "/img/timeline/pong.png"
    date: ""
    description: "<h4><a href='http://chyiyenwang.github.io/My-Game/' target='_blank'>Pong</a></h4><small>A front end web app created using the HTML5 Canvas API. This project was inspired by the Atari game of the same name - Pong. I have always been and still am a big gamer and I decided to create a video game myself so I thought to myself why not make a game in homage of Pong.</small>"

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "chyiyenwang@gmail.com"

##################
# Social Buttons #
##################

social:
  - title: "twitter"
    url: "https://twitter.com/chyiyenwang"
  - title: "github"
    url: "https://github.com/chyiyenwang"
  - title: "linkedin"
    url: "https://linkedin.com/in/chyiyenwang"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  # Blog: 'latest-post'
  Projects: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
